### ISSUE TITLE
If I'm selecting, it doesn't end the game if my opponent concedes.

### ISSUE THREAD

**Issue by Hill-98** [Hastwell/Omukade.Cheyenne#17]
For example, if I use Great Ball to selecting a Pokémon, I won't get a concede message if my opponent concedes.

This bug is probably caused by 0b1e297 and the problem should be in the `IsEndOperation` method.

If I change the method to the following code there is no problem, but I'm not sure if there are any other operations that are defined as "end" or not

```C#
public static bool IsEndOperation(OperationType operationType) => operationType == OperationType.End || operationType == OperationType.Quit || operationType == OperationType.TimeoutForceQuit;
```

`operationType == OperationType.Quit`

**Comment by Hastwell** [comment]
It looks like I caused this regression by accidentally removing `Quit` as valid operation type for this check. The correct fix, which will be coming shortly, would be:
```C#
public static bool IsQuitOperation(OperationType operationType) => operationType == OperationType.Quit || operationType == OperationType.TimeoutForceQuit;
```

`End` has no special properties and is mainly used to signify "all done" when placing Pokemon at the start of the game, and to indicate your turn is done. You should not be able to bypass checks for this (think eg, starting the game with no Pokemon)
