### ISSUE TITLE
Hello, about commercial use code

### ISSUE THREAD

**Issue by 2678674360** [Hastwell/Omukade.Cheyenne#7]
Hello,  

As I Know, someone in china is using your source code to create a third-party server for profit, and can use the commonality between the third-party server and the official server to transfer some data to the official server. Is it okay if I also want to make a profit like this? Could I be able  to pay the usage fee and make it my exclusive use? 

Looking forward to hearing from you 
QQ2678674360@outlook.com
Thanks

**Comment by beiyanpiki** [comment]
Any source?

**Comment by typesana** [comment]
Regardless of your intentions in raising this issue, your act of impersonating my identity using my personal QQ number has made me angry. Please use your own account. Already reported.

**Comment by Cometocurse** [comment]
操你妈，注册个号来骂你，眼红群主是吧！

**Comment by Cometocurse** [comment]
看到别人赚钱就嫉妒他

**Comment by Cometocurse** [comment]
You are jealous when you see the group owner making money.

**Comment by Junglemania** [comment]
I sent several posts to scold you, which were automatically deleted by the system, and Chinese was not allowed to be used. Let me help the group owner scold you.

**Comment by DKeresh** [comment]
The foolish chinese are always bickering over profits. As soon as one person makes money, another becomes envious and strives to do the same. The most unfortunate are the code authors, who, unknowingly, are treated as mere tools for profit-making and even as free customer service, expected to resolve any issue that arises. The original intention of the author was not to release the source code for the chinese players, yet they continue to quarrel over profit. It's truly laughable, and that's why I don't like them!

**Comment by Hastwell** [comment]
***This is not legal advice. Please do not attempt to do this. You are strongly encouraged to seek professional council if you choose to continue with this action anyway.***

Although the AGPL v3.0 license that covers this project does not prohibit commercial use, this is _strongly_ not recommended for a variety of reasons:
* TPC/TPCi and their respective parent companies have historically taken significant adverse action against parties infringing on their IP rights for monetary gain. You may place yourself into a position of extreme, potentially unlimited liability by effectively reselling access to TPC/TPCi assets and IP.

* Any operator that makes unreasonable compensation demands for use of their Cheyenne instance will likely be abandoned by its users for another Cheyenne operator.

* Any party that operates a fork of Cheyenne can, under the terms of the AGPL, be required to produce the source code to any changes made to their version, which can then be used in other Cheyenne forks or even integrated into the official Cheyenne source code without further compensation.

* Exclusivity is not very applicable under the AGPL license, as any party that already has the source code (and thus operates under the AGPL license) can continue to use and develop that version of Cheyenne regardless of any exclusivity agreement that may be reached. (a similar situation resulted in the creation of AWS OpenSearch, which forked from ElasticSearch)

* Cheyenne is still alpha-quality software that barely works, is barely tested, still has bugs, and frequently experiences new bugs. By collecting a usage fee, you may be implying to users that the software has a level of quality and reliability that in fact does not exist, does not guarantee any level of quality as stated under the terms of the AGPL, may stop working at any time without warning, and provides no SLA to guarantee timely (or any) fixes for issues.

As for contact with official servers, Cheyenne's only contact with the official game servers is to retrieve updates to the game and rule/card mechanics. Players of a Cheyenne server do not use the official servers for core gameplay, although they are used to store decklists and maintain friend lists for consistency when switching between official servers and various Cheyenne servers.

Finally, the above points aside, I would not accept exclusivity agreements for this software anyway, as that would defeat one of the primary reasons for its creation.

As this issue has drifted off-topic to include non-constructive personal insults, it will be locked. I will not further entertain this subject matter.
